apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: infra
  description: test adding componant
  annotations:
    kubernetes.io/cluster-name: management-cluster
    backstage.io/kubernetes-label-selector: 'app' 
#    backstage.io/kubernetes-id: my-service 
    kubernetes.io/namespace: crossplane-system
  tags:
    - website
spec:
  type: service
  lifecycle: production
  owner: infrastructure-team
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: amazon-eks-clusters
  description: "Clusters Amazon EKS provisionnés via Crossplane"
  annotations:
    kubernetes.io/cluster-name: management-cluster
    backstage.io/kubernetes-label-selector: 'cluster.upbound.io/amazoneks'
    kubernetes.io/namespace: default
spec:
  type: resource
  lifecycle: production
  owner: infrastructure-team
  system: cloud-platform
