apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: infra
  description: test adding componant
  annotations:
    kubernetes.io/cluster-name: management-cluster
    backstage.io/kubernetes-label-selector: 'app' 
#    backstage.io/kubernetes-id: my-service 
    kubernetes.io/namespace: crossplane-system
  tags:
    - website
spec:
  type: service
  lifecycle: production
  owner: infrastructure-team
  system: cloud-platform
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: cloud-platform
  description: "Plateforme cloud basée sur Crossplane"
spec:
  owner: infrastructure-team
  domain: infrastructure
---

